a = input('digite algo:')
print('O tipo primitivo desse valor é ', type(a))
print('so tem espaços', a.isspace())
print('é um numero', a.isnumeric())
print('é alfabetico', a.isalpha())
print('e alphanumerico', a.isalnum())
print('is it in small leters', a.islower())
print('is it in large letters', a.isupper())
print('is it captalized', a.istitle())